import Head from 'next/head'
import { Inter } from 'next/font/google'
import Chart from '@/components/chart'
import { useRouter } from 'next/router'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    const router = useRouter();
    const { id } = router.query;


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4 md:p-10 mx-auto max-w-7xl">
        <Chart id={id}/>



      </main>
    </>
  )
}
